---
language: python
python: '2.7'
dist: 'trusty'

env:
  - SITE=itedd.yml

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo service stop postgresql

install:
  # Install Ansible
  - pip install ansible
  - ansible --version
  # Configure Ansible
  - cp tests/ansible.cfg .
  - export ANSIBLE_ROLES_PATH=$PWD
  # Install 3rd party roles
  - 'ansible-galaxy install -r tests/Rolefile.yml'

script:
  - 'ansible-playbook -i tests/inventory tests/$SITE --sudo'
