FROM travisci/ubuntu-systemd:18.04

# Install Ansible
RUN apt-get update && apt-get install -y \
  software-properties-common \
  git \
  sudo \
  apt-transport-https \
  init \
  iproute2 \
  locales \
&& apt-add-repository -y ppa:ansible/ansible \
&& apt-get update && apt-get install -y ansible \
&& localedef -i en_US -f UTF-8 en_US.UTF-8

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
