#
# Keep only a defined amount of releases, delete the oldest if more exist
#
---
- name: Cleanup
  shell: >
    ls -dt {{ RAILS_APP_RELEASES_PATH }}/*
    | egrep '{{ rails_deploy_release_mask }}'
    | tail -n +{{ rails_deploy_old_release_count }}
    | xargs rm -rfv
  register: rails_cleanup_result
  changed_when: >
    'removed' in rails_cleanup_result.stdout
