- name: Update cronjobs for app
  command: "{{ profile }}'bundle exec whenever --set environment={{ rails_env}} --update-crontab {{ app_name }}'"
  args:
    chdir: "{{ RAILS_APP_RELEASE_PATH }}"
  register: rails_whenever_result
