#
# Perform the asset:precompile rake task
#
---
- name: Precompile assets
  command: "{{ profile }}'bundle exec rake assets:precompile'"
  args:
    chdir: "{{ RAILS_APP_RELEASE_PATH }}"
  register: rails_compile_assets_result
  changed_when: >
    'Writing' in rails_compile_assets_result.stdout
